# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-29 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=200)),
                ('switch_status', models.CharField(choices=[('on', 'switch is oN'), ('off', 'switch is oFF')], max_length=2)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Home')),
            ],
        ),
    ]
