# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181101_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
