# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181101_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='temperature_user_set',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
